### ISSUE TITLE
Does this library support Redux or dynamic rendering?

### ISSUE THREAD

**Issue by jarvisluong** [thegamenicorus/react-native-timeline-listview#5]
I want to use this library to one of my project that when user swipe to the top of the timeline, it can show a loading indicator and then update the timeline, and when the user swipe to near the end of the timeline, the timeline will automatically update more data and append to the timeline

**Comment by thegamenicorus** [comment]
Hello @jarvisluong.

Yes. Since the library 'react-native-timeline-listview' based on ListView component. We can use build-in methodology in react-native with this library to implement 'pull-to-refresh' and 'load more' function.

I recommend [RefreshControl](https://facebook.github.io/react-native/docs/refreshcontrol.html) to add 'pull-to-refresh' to your timeline. For 'load-more' you can use **onEndReached** and **renderFooter** from ListView component.

You can see [this example](https://facebook.github.io/react-native/docs/refreshcontrol.html) for more detail.

Alternative way of 'load-more', you might use [infinite scroll view library](https://github.com/expo/react-native-infinite-scroll-view), But I didn't try yet.

Enjoy coding. 👍
